### ISSUE TITLE
Add to Flathub

### ISSUE THREAD

**Issue by GEkuL** [jedisct1/minisign#131]
The tool looks helpful, but I can't get it easily on my linux device without installing it via Docker.
Could you please add the tool to [Flathub](https://flathub.org), so it could b e easily downloaded for any linux flavor.

Thanks!

**Comment by jedisct1** [comment]
HI!

Why not. But I use a Mac, and don't know anything about Flahub.

Since you do, could you possibly help with the required package definitions and maybe a way to build it using GitHub Actions?

That being said, for distros that don't have package for it, precompiled binaries for Linux have always been available here: https://jedisct1.github.io/minisign/
