### ISSUE TITLE
 Secret key format (Documentation)

### ISSUE THREAD

**Issue by duesee** [jedisct1/minisign#29]
Hey, as of the documentation, the `keynum_sk` contains the `<secret_key>` and `<public_key>`. On the other side, `checksum` does only contain the `<secret_key>`. Probably `<secret_key>` means pub + sec, but it seems inconsistent to use it like this. Reading the code, the checksum is made over both, the public and the private key, right?

**Comment by jedisct1** [comment]
Good catch!

Indeed, the checksum includes the public key. I'm going to update the documentation accordingly.

Thanks for spotting this!

**Comment by duesee** [comment]
That was fast :-) 👍 May I ask a question? You say that minisign uses a slightly different format to store secret keys as signify. Unfortunately, I am not able to find a definition for signify's formats... Can you point me to the right direction or explain what your motivation was to introduce the difference?

**Comment by jedisct1** [comment]
I wasn't able to find a definition of signify's formats either, besides the source code itself.

But signify's secret key format is:
```
<signature_algorithm> || <kdf_algorithm> ||<kdf_params> || <cksum> || <key_id> || E(<secret_key> || <public_key>)
```
with `cksum = H(<secret_key> || public<key>)`.

Minisign format is:
```
<signature_algorithm> || <kdf_algorithm> || <cksum_algorithm> || <kdf_params> || E(<key_id> || <secret_key> || <public_key> || <cksum>))
```
with `cksum = H(<signature_algorithm> || <key_id> || <secret_key> || public<key>)`.

In both cases, the sole purpose of the checksum is to verify that the key derived from the password is likely to be the one initially used to encrypt the signing key.

Both include the public key in the computation of the checksum, which primarily helps against algorithm downgrades, but can also help against fault injection on the sk. For the former, including the algorithm in the checksum computation is not necessarily redundant since the same key pair can be valid with multiple signing systems, especially if they happen to include prehashing without explicit context separation. In its current state, it makes no difference.

Minisign encrypts the key identifier and the key, signify doesn't. It doesn't make any practical difference. signify's checksum will immediately expose a weak key, minisign won't, but that protection limited to the scope of the secret key file.

Signify uses SHA2 as a hash function and bcrypt as a KDF. Minisign uses BLAKE2 as a hash function and scrypt as a KDF. Besides the memory-hardness provided by scrypt, the choice of these functions over signify's ones was simply motivated by them being already available in libsodium, even in minimum builds.
While being able to verify signatures using either tool can be useful, there was no major incentive for having a compatible format for storing secret keys.

By the way of libsodium, minisign offers limited protection against injection by rejecting weak public keys and small order nonces during verification. The outcome of the verification is also checked multiple times.

But neither minisign nor signify claim to offer any resistance against fault injections.

**Comment by duesee** [comment]
Thanks for the detailed reply!

`Both include the public key in the computation of the checksum, which primarily helps against algorithm downgrades, but can also help against fault injection on the sk.`

It also helps against fault injections in the public key :-)

I don't think that any program should claim to be resistent against fault injections. But some schemes may be more vulnerable than others -- maybe for no good reason.

We used Minisign as our first test program for experimentation because of its simplicity. I will report back, when we are done. I think we will suggest one minor change to minisign, but I'm looking forward for your opinion on this.

**Comment by jedisct1** [comment]
No problem! And any suggestion for improving this tool would be more than welcome!
