### ISSUE TITLE
Please Add Support for Schoor Threshold Signatures

### ISSUE THREAD

**Issue by tarrenj** [jedisct1/minisign#86]
I'd like to perform a multisignature without increasing the size of the detached signature, and still be able to determine which unique keys contributed to the multisig and which ones haven't. I believe Schoor Threshold Signatures would do this? I'm in over my head with this, so please forgive me if I'm completely wrong here.

I'd like to use Minisign for this since it's so simple, but if I'm going about this all wrong just let me know.
Thanks!

**Comment by tarrenj** [comment]
Actually, it looks like support would first need to be added to LibSodium.  I'll wait a while for feedback here before asking over there to prevent spamming.

**Comment by jedisct1** [comment]
That would be a completely different tool.

Unless you have a lot of signers because you are building a blockchain, an aggregate signature is probably not required. Have the different parties send their signature individually, and the verifier can check who signed and who didn't (especially since this is apparently what you want, not a threshold).

So, I don't know, maybe some day I'll write a tool using aggregate signatures, if I ever need that, but this is not planned in a near future :)

Aggregate/threshold signatures are not planned for libsodium either (see the roadmap) but that may change once some schemes get standardized, and if I have use cases for them.

I will probably implement BLS signatures in Zig before libsodium, though.

**Comment by tarrenj** [comment]
Thanks for the info! The use case is over a pretty unstable satellite connection (lots of dropped packets...), so I'd like to keep the number of messages being sent out of the system to a minimum to cut down on re-transmission, so even though there are only ~15 signers, I'd still like to find an aggregate signature solution. I hadn't seen BLS signatures before, so thanks for pointing them out, I may just use those instead and deal with the re-transmissions to keep things simpler.

It actually looks like [MuSig-DE](https://medium.com/blockstream/musig-dn-schnorr-multisignatures-with-verifiably-deterministic-nonces-27424b5df9d6) may accomplish what I'm looking for, but if it doesn't I'll look more into BLS sigs.

**Comment by jedisct1** [comment]
If you're looking for threshold signatures, and minimizing round trips is important, take a look a FROST (which is likely to get standardized).
